//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class channel
    {
        public channel()
        {
            this.channel_field = new HashSet<channel_field>();
        }
    
        public int id { get; set; }
        public Nullable<int> site_id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public Nullable<byte> is_albums { get; set; }
        public Nullable<byte> is_attach { get; set; }
        public Nullable<byte> is_spec { get; set; }
        public Nullable<int> sort_id { get; set; }
    
        public virtual channel_site channel_site { get; set; }
        public virtual ICollection<channel_field> channel_field { get; set; }
    }
}
