//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlueEntities : DbContext
    {
        public BlueEntities()
            : base("name=dbcc6ecb5cc89b4edda5faa6c9008a7850Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dt_article> dt_article { get; set; }
        public DbSet<dt_article_albums> dt_article_albums { get; set; }
        public DbSet<dt_article_attach> dt_article_attach { get; set; }
        public DbSet<dt_article_attribute_field> dt_article_attribute_field { get; set; }
        public DbSet<dt_article_attribute_value> dt_article_attribute_value { get; set; }
        public DbSet<dt_article_category> dt_article_category { get; set; }
        public DbSet<dt_article_comment> dt_article_comment { get; set; }
        public DbSet<dt_channel> dt_channel { get; set; }
        public DbSet<dt_channel_field> dt_channel_field { get; set; }
        public DbSet<dt_channel_site> dt_channel_site { get; set; }
        public DbSet<dt_express> dt_express { get; set; }
        public DbSet<dt_feedback> dt_feedback { get; set; }
        public DbSet<dt_link> dt_link { get; set; }
        public DbSet<dt_mail_template> dt_mail_template { get; set; }
        public DbSet<dt_manager> dt_manager { get; set; }
        public DbSet<dt_manager_log> dt_manager_log { get; set; }
        public DbSet<dt_manager_role> dt_manager_role { get; set; }
        public DbSet<dt_manager_role_value> dt_manager_role_value { get; set; }
        public DbSet<dt_navigation> dt_navigation { get; set; }
        public DbSet<dt_order_goods> dt_order_goods { get; set; }
        public DbSet<dt_orders> dt_orders { get; set; }
        public DbSet<dt_payment> dt_payment { get; set; }
        public DbSet<dt_sms_template> dt_sms_template { get; set; }
        public DbSet<dt_user_amount_log> dt_user_amount_log { get; set; }
        public DbSet<dt_user_code> dt_user_code { get; set; }
        public DbSet<dt_user_group_price> dt_user_group_price { get; set; }
        public DbSet<dt_user_groups> dt_user_groups { get; set; }
        public DbSet<dt_user_login_log> dt_user_login_log { get; set; }
        public DbSet<dt_user_message> dt_user_message { get; set; }
        public DbSet<dt_user_oauth> dt_user_oauth { get; set; }
        public DbSet<dt_user_oauth_app> dt_user_oauth_app { get; set; }
        public DbSet<dt_user_point_log> dt_user_point_log { get; set; }
        public DbSet<dt_user_recharge> dt_user_recharge { get; set; }
        public DbSet<dt_users> dt_users { get; set; }
        public DbSet<dt_user_attach_log> dt_user_attach_log { get; set; }
    }
}
