//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbContent : DbContext
    {
        public DbContent()
            : base("name=dbcc6ecb5cc89b4edda5faa6c9008a7850Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<article> article { get; set; }
        public DbSet<article_albums> article_albums { get; set; }
        public DbSet<article_attach> article_attach { get; set; }
        public DbSet<article_attribute_field> article_attribute_field { get; set; }
        public DbSet<article_attribute_value> article_attribute_value { get; set; }
        public DbSet<article_category> article_category { get; set; }
        public DbSet<article_comment> article_comment { get; set; }
        public DbSet<channel> channel { get; set; }
        public DbSet<channel_field> channel_field { get; set; }
        public DbSet<channel_site> channel_site { get; set; }
        public DbSet<express> express { get; set; }
        public DbSet<feedback> feedback { get; set; }
        public DbSet<link> link { get; set; }
        public DbSet<mail_template> mail_template { get; set; }
        public DbSet<manager> manager { get; set; }
        public DbSet<manager_log> manager_log { get; set; }
        public DbSet<manager_role> manager_role { get; set; }
        public DbSet<manager_role_value> manager_role_value { get; set; }
        public DbSet<navigation> navigation { get; set; }
        public DbSet<order_goods> order_goods { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<sms_template> sms_template { get; set; }
        public DbSet<user_amount_log> user_amount_log { get; set; }
        public DbSet<user_code> user_code { get; set; }
        public DbSet<user_group_price> user_group_price { get; set; }
        public DbSet<user_groups> user_groups { get; set; }
        public DbSet<user_login_log> user_login_log { get; set; }
        public DbSet<user_message> user_message { get; set; }
        public DbSet<user_oauth> user_oauth { get; set; }
        public DbSet<user_oauth_app> user_oauth_app { get; set; }
        public DbSet<user_point_log> user_point_log { get; set; }
        public DbSet<user_recharge> user_recharge { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<user_attach_log> user_attach_log { get; set; }
    }
}
