//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_article_attribute_value
    {
        public int article_id { get; set; }
        public string sub_title { get; set; }
        public string source { get; set; }
        public string author { get; set; }
        public string goods_no { get; set; }
        public Nullable<int> stock_quantity { get; set; }
        public Nullable<decimal> market_price { get; set; }
        public Nullable<decimal> sell_price { get; set; }
        public Nullable<int> point { get; set; }
        public string video_src { get; set; }
    
        public virtual dt_article dt_article { get; set; }
    }
}
