//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_article_comment
    {
        public int id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> article_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public string user_ip { get; set; }
        public string content { get; set; }
        public Nullable<byte> is_lock { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<byte> is_reply { get; set; }
        public string reply_content { get; set; }
        public Nullable<System.DateTime> reply_time { get; set; }
    }
}
