//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_channel_field
    {
        public int id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> field_id { get; set; }
    
        public virtual dt_article_attribute_field dt_article_attribute_field { get; set; }
        public virtual dt_channel dt_channel { get; set; }
    }
}
