//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_channel_site
    {
        public dt_channel_site()
        {
            this.dt_channel = new HashSet<dt_channel>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string build_path { get; set; }
        public string templet_path { get; set; }
        public string domain { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string crod { get; set; }
        public string copyright { get; set; }
        public string seo_title { get; set; }
        public string seo_keyword { get; set; }
        public string seo_description { get; set; }
        public Nullable<byte> is_default { get; set; }
        public Nullable<int> sort_id { get; set; }
    
        public virtual ICollection<dt_channel> dt_channel { get; set; }
    }
}
