//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_mail_template
    {
        public int id { get; set; }
        public string title { get; set; }
        public string call_index { get; set; }
        public string maill_title { get; set; }
        public string content { get; set; }
        public Nullable<byte> is_sys { get; set; }
    }
}
