//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_manager
    {
        public int id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> role_type { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string real_name { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<int> is_lock { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    
        public virtual dt_manager_role dt_manager_role { get; set; }
    }
}
