//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_manager_role
    {
        public dt_manager_role()
        {
            this.dt_manager = new HashSet<dt_manager>();
            this.dt_manager_role_value = new HashSet<dt_manager_role_value>();
        }
    
        public int id { get; set; }
        public string role_name { get; set; }
        public Nullable<byte> role_type { get; set; }
        public Nullable<byte> is_sys { get; set; }
    
        public virtual ICollection<dt_manager> dt_manager { get; set; }
        public virtual ICollection<dt_manager_role_value> dt_manager_role_value { get; set; }
    }
}
