//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_navigation
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public string nav_type { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string sub_title { get; set; }
        public string icon_url { get; set; }
        public string link_url { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<byte> is_lock { get; set; }
        public string remark { get; set; }
        public string action_type { get; set; }
        public Nullable<byte> is_sys { get; set; }
    }
}
