//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_user_groups
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<int> upgrade_exp { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<byte> is_default { get; set; }
        public Nullable<byte> is_upgrade { get; set; }
        public Nullable<byte> is_lock { get; set; }
    }
}
