//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager_role
    {
        public manager_role()
        {
            this.manager = new HashSet<manager>();
            this.manager_role_value = new HashSet<manager_role_value>();
        }
    
        public int id { get; set; }
        public string role_name { get; set; }
        public Nullable<byte> role_type { get; set; }
        public Nullable<byte> is_sys { get; set; }
    
        public virtual ICollection<manager> manager { get; set; }
        public virtual ICollection<manager_role_value> manager_role_value { get; set; }
    }
}
